spring.application.name=sandboxpro
server.port=8080

spring.data.mongodb.uri=mongodb+srv://snehapradhan1702_db_user:sneha3456@cluster0.u7ka2pv.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=notesdb

gemini.api.key=gen-lang-client-0612762122
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent

jwt.secret=MyAnatomyWorkshopSuperSecretKeyFor256BitHmacSha2026!
jwt.expiration-ms=86400000

logging.level.com.myanatomy=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG